version: '3.9'
services:
  node:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: challenge-node-backend
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
      - /app/node_modules
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: challenge-react-frontend
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/app